// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableAwsRawEvents {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub payload: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub context: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "4")]
    pub deadline: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "5")]
    pub ingested_at: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "6")]
    pub ingested_date: ::core::option::Option<i32>,
}
