// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableSqsMessages {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub receipt_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub body: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub md5_of_body: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub md5_of_message_attributes: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "6")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, message", tag = "7")]
    pub message_attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        table_sqs_messages::MessageAttributes,
    >,
    #[prost(string, optional, tag = "8")]
    pub queue_arn: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub aws_region: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "10")]
    pub ingested_at: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "11")]
    pub ingested_date: ::core::option::Option<i32>,
}
/// Nested message and enum types in `table_sqs_messages`.
pub mod table_sqs_messages {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct MessageAttributes {
        #[prost(string, optional, tag = "1")]
        pub string_value: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(bytes = "vec", optional, tag = "2")]
        pub binary_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        #[prost(string, repeated, tag = "3")]
        pub string_list_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(bytes = "vec", repeated, tag = "4")]
        pub binary_list_values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
        #[prost(string, optional, tag = "5")]
        pub data_type: ::core::option::Option<::prost::alloc::string::String>,
    }
}
